export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_TOP_PRODUCTS = "FETCH_TOP_PRODUCTS";
export const FETCH_BEST_PRODUCTS = "FETCH_BEST_PRODUCTS";
export const UPDATE_FILTER = "UPDATE_FILTER";
